/**
 * H2MS API
 * API for interacting with the H2MS backend.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GrantedAuthority } from './grantedAuthority';
import { Role } from './role';
import {Link} from './link';


export interface User {
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    authorities?: Array<GrantedAuthority>;
    createdOn?: string;
    credentialsNonExpired?: boolean;
    email?: string;
    enabled?: boolean;
    firstName?: string;
    id?: number;
    lastLogin?: string;
    lastName?: string;
    _links?: Link;
    middleName?: string;
    notificationFrequency?: string;
    resetToken?: string;
    roles?: Array<Role>;
    type?: string;
    verified?: string;
}
