package com.milaboratory.core.alignment;

import com.milaboratory.core.sequence.NucleotideSequence;
import org.junit.Test;

public class AlignmentHelperTest {
    @Test
    public void test1() throws Exception {
        NucleotideSequence seq1 = new NucleotideSequence("GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTATAGCATGAACTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTTTCATACATTAGTAGTAGTAGTAGTACCATATACTACGCAGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAATGCCAAGAACTCACTGTATCTGCAAATGAACAGCCTGAGAGACGAGGACACGGCTGTGTATTACTGTGC");
        NucleotideSequence seq2 = new NucleotideSequence("GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCCTGGTCAAGCCTGGGGGGTCCATGAGACACTCCTGTGCAGCCTCTGGATTCCCCTTCAGTACTTATAGCATGAACTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCTCATCCATTAGTAGTGGTAGTAGTTACATATATTACGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAACTCACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGC");
        Alignment<NucleotideSequence> alignemnt = Aligner.alignLocal(LinearGapAlignmentScoring.getNucleotideBLASTScoring(), seq1, seq2);
        for (AlignmentHelper alignmentHelper : alignemnt.getAlignmentHelper().split(30, 5)) {
            System.out.println(alignmentHelper);
            System.out.println();
        }
    }
}