DROP DATABASE H2MSDatabase;
CREATE DATABASE H2MSDatabase;
USE H2MSDatabase;

CREATE TABLE EVENT (
       ID INT(10) NOT NULL AUTO_INCREMENT
     , FORM_NAME VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID)
);
